(function () {
  "use strict";

  const app = new window.RingMapChart.Controller({
    svg: document.getElementById("chartCanvas"),
    pathTrail: document.getElementById("pathTrail"),
    mapSelect: document.getElementById("mapSelect"),
    parentMapButton: document.getElementById("parentMapButton"),
    childMapButton: document.getElementById("childMapButton"),
    newMapButton: document.getElementById("newMapButton"),
    deleteMapButton: document.getElementById("deleteMapButton"),
    newMindButton: document.getElementById("newMindButton"),
    saveMindButton: document.getElementById("saveMindButton"),
    exportMindButton: document.getElementById("exportMindButton"),
    importMindInput: document.getElementById("importMindInput"),
    clearRecentMindsButton: document.getElementById("clearRecentMindsButton"),
    mindMenu: document.querySelector(".mind-menu"),
    titleInput: document.getElementById("titleInput"),
    settingsMenu: document.querySelector(".settings-menu"),
    saveState: document.getElementById("saveState"),
    commandPaletteButton: document.getElementById("commandPaletteButton"),
    commandPalette: document.getElementById("commandPalette"),
    commandInput: document.getElementById("commandInput"),
    commandResults: document.getElementById("commandResults"),
    viewModeInput: document.getElementById("viewModeInput"),
    themePresetInput: document.getElementById("themePresetInput"),
    stylePresetInput: document.getElementById("stylePresetInput"),
    navigationModeInput: document.getElementById("navigationModeInput"),
    customThemeEditor: document.getElementById("customThemeEditor"),
    branchPalette: document.getElementById("branchPalette"),
    shufflePaletteButton: document.getElementById("shufflePaletteButton"),
    resetPaletteButton: document.getElementById("resetPaletteButton"),
    exportThemeButton: document.getElementById("exportThemeButton"),
    importThemeInput: document.getElementById("importThemeInput"),
    nodeLabelInput: document.getElementById("nodeLabelInput"),
    nodeActionBar: document.getElementById("nodeActionBar"),
    nodeEditor: document.getElementById("nodeEditor"),
    addButton: document.getElementById("addButton"),
    renameButton: document.getElementById("renameButton"),
    openMapButton: document.getElementById("openMapButton"),
    reparentButton: document.getElementById("reparentButton"),
    noteButton: document.getElementById("noteButton"),
    noteSidebar: document.getElementById("noteSidebar"),
    noteSidebarTitle: document.getElementById("noteSidebarTitle"),
    nodeStatusInput: document.getElementById("nodeStatusInput"),
    nodePriorityInput: document.getElementById("nodePriorityInput"),
    nodeMarkerInput: document.getElementById("nodeMarkerInput"),
    nodeTagsInput: document.getElementById("nodeTagsInput"),
    noteInput: document.getElementById("noteInput"),
    nodeLinkSuggest: document.getElementById("nodeLinkSuggest"),
    noteLinks: document.getElementById("noteLinks"),
    backlinks: document.getElementById("backlinks"),
    closeNoteButton: document.getElementById("closeNoteButton"),
    welcomeDialog: document.getElementById("welcomeDialog"),
    welcomeStats: document.getElementById("welcomeStats"),
    welcomeTemplates: document.getElementById("welcomeTemplates"),
    welcomeStyles: document.getElementById("welcomeStyles"),
    welcomeRecent: document.getElementById("welcomeRecent"),
    welcomeCloseButton: document.getElementById("welcomeCloseButton"),
    welcomeCommandButton: document.getElementById("welcomeCommandButton"),
    deleteButton: document.getElementById("deleteButton"),
    resetButton: document.getElementById("resetButton"),
    statusText: document.getElementById("statusText"),
    spacingInputs: {
      treeLevelGap: document.getElementById("treeLevelGapInput"),
      treeLeafGap: document.getElementById("treeLeafGapInput"),
      ringBaseRadius: document.getElementById("ringBaseRadiusInput"),
      ringDepthGap: document.getElementById("ringDepthGapInput"),
      ringNodeGap: document.getElementById("ringNodeGapInput")
    },
    appearanceInputs: {
      nodeFontSize: document.getElementById("nodeFontSizeInput")
    },
    appearanceToggles: {}
  });

  app.start();
})();
